
import PhotoImage from "../components/Photo/Photo";
import Title from "../components/Title/Title";
import styles from "./photo.module.css";
import PhotoComponents from "./PhotoComponents";

export const metadata = {
    title: "HiRes Studio — Фото",
    description: "Generated by create next app",
    icons: {
        icon: '/logo.svg'
    }
  };
  

export default function Photo() {
  return (
    <div className={styles.main}>
        <PhotoComponents />
        <div className={styles.kenost}>
            <div className={`container ${styles.container}`}>


                <Title padding="false" text="Январь 2024" />
                <div className={styles.PhotoContainer}>
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                </div>

                <Title text="Январь 2024" />
                <div className={styles.PhotoContainer}>
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                </div>

                <Title text="Январь 2024" />
                <div className={styles.PhotoContainer}>
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                    <PhotoImage />
                </div>
            </div>
        </div>
    </div>
  )
}
